mail_management_backoffice/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace mail_management_backoffice.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

mail_management_backoffice/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mail_management_backoffice.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

mail_management_backoffice/Pages/Login.cshtml.cs
using mail_management_backoffice.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mail_management_backoffice.Pages
{
    public class LoginModel : PageModel
    {
        public SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public Login Model { get; set; }

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if(ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = Model.Email,
                    Email = Model.Email
                };

                var identifyResult = await signInManager.PasswordSignInAsync(Model.Email, Model.Password, Model.RememberMe, false);
                //var identifyResult = await signInManager.CheckPasswordSignInAsync(user, Model.Password, false);

                if (identifyResult.Succeeded)
                {
                    if(returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Mails/Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }

                ModelState.AddModelError("", "Username or Password Incorrect");
            }

            return Page();
        }
    }
}

mail_management_backoffice/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mail_management_backoffice.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> SignInManager;
        public LogoutModel(SignInManager<IdentityUser> signInManager) {
            this.SignInManager = signInManager; 
        }    
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await SignInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostDontLogout()
        {
            return RedirectToPage("Mails/Index");
        }
    }
}

mail_management_backoffice/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mail_management_backoffice.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

mail_management_backoffice/Pages/Register.cshtml.cs
using mail_management_backoffice.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace mail_management_backoffice.Pages
{
    public class RegisterModel : PageModel
    {
        public UserManager<IdentityUser> UserManager;  
        public SignInManager<IdentityUser> SignInManager;

        [BindProperty]
        public Register Model {  get; set; }

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.UserManager = userManager;
            this.SignInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync() { 
            if(ModelState.IsValid) {
                var user = new IdentityUser()
                {
                    UserName = Model.Email,
                    Email = Model.Email
                };

                var result = await UserManager.CreateAsync(user, Model.Password);
                if(result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("/Register");
                }

                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return Page();
        }   
    }
}

mail_management_backoffice/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="row mb-auto">
    <div class="col-md-4">
        <div class="row no-gutters border mb-4">
            <div class="col p-4 mb-4 ">
                <p class="card-text">
                    Mail Management is a sample application that
                    demonstrates how to use Entity Framework Core in an
                    ASP.NET Core Razor Pages web app.
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="row no-gutters border mb-4">
            <div class="col p-4 d-flex flex-column position-static">
                <p class="card-text mb-auto">
                    You can build the application by following the steps in a series of tutorials.
                </p>
                <p>
@*                    <a href="https://docs.microsoft.com/aspnet/core/data/ef-rp/intro" class="stretched-link">See the tutorial</a>
*@                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="row no-gutters border mb-4">
            <div class="col p-4 d-flex flex-column">
                <p class="card-text mb-auto">
                    You can download the completed project from GitHub.
                </p>
                <p>
@*                    <a href="https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/ef-rp/intro/samples" class="stretched-link">See project source code</a>
*@                </p>
            </div>
        </div>
    </div>
</div>

mail_management_backoffice/Pages/Login.cshtml
@page
@model mail_management_backoffice.Pages.LoginModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email Address</label>
                    <input type="text" asp-for="Model.Email" class="form-control"/>
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control"/>
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input"/>
                    <label class="form-check-label" asp-for="Model.RememberMe">Remember me ?</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

mail_management_backoffice/Pages/Logout.cshtml
@page
@model mail_management_backoffice.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row jusitfy-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>
                    Are you sure you want to logout ? 
                </p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light m-lg-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

mail_management_backoffice/Pages/Register.cshtml
@page
@model mail_management_backoffice.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger">

                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email Address</label>
                    <input type="text" asp-for="Model.Email" class="form-control"/>
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control"/>
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="Model.ConfirmPassword" class="form-control"/>
                    <span asp-validation-for="Model.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>